version: '3.8'

services:
  # Spring Boot App
  spring:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: kkh-app
    expose:
      - "8080"
    depends_on:
      - mysql
      - redis
      - mongodb
    networks:
      - backend-bridge


  # Nginx Proxy
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - spring
    networks:
      - backend-bridge

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: kkh-mysql
    ports:
      - '4306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - backend-bridge

  # Redis
  redis:
    image: redis:7.2.5
    container_name: kkh-redis
    ports:
      - '6379:6379'
    networks:
      - backend-bridge

  # MongoDB
  mongodb:
    image: mongo:6.0.16
    container_name: kkh-mongodb
    ports:
      - '37017:27017'
    volumes:
      - ./mongodb/data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      - backend-bridge

  # Elasticsearch
  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - node.name=single-node
      - cluster.name=backtony
      - discovery.type=single-node
    ports:
      - "${ES_HTTP_PORT}:9200"
      - "${ES_TRANSPORT_PORT}:9300"
    networks:
      - es-bridge
      - backend-bridge

  # Kibana
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on:
      - es
    networks:
      - es-bridge
      - backend-bridge


networks:
  es-bridge:
    driver: bridge
  backend-bridge:
    driver: bridge
