services:

  ### 키키하이 도커 이미지
  spring:
    image: kikihi/server:latest
    container_name: kkh-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - mongodb
    networks:
      - backend-bridge

  # Nginx Proxy
  nginx:  # nginx 서비스 정의
    image: nginx:latest  # 사용할 Docker 이미지
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /letsencrypt/certbot/conf:/etc/letsencrypt
      - /letsencrypt/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - spring
    networks:
      - backend-bridge
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /letsencrypt/certbot/conf:/etc/letsencrypt
      - /letsencrypt/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - backend-bridge
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: kkh-mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - backend-bridge

  # Redis
  redis:
    image: redis:7.2.5
    container_name: kkh-redis
    ports:
      - '6379:6379'
    networks:
      - backend-bridge

  # MongoDB
  mongodb:
    image: mongo:6.0.16
    container_name: kkh-mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb/data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      - backend-bridge


networks:
  backend-bridge:
    driver: bridge
